#!/usr/bin/env python3

u"""
 This is the main program which takes a pre-calculated model file and corresponding sample features. The program returns
 the corresponding classification likelihood for each datum and class in the form of a (negatively log-scaled)
 likelihood matrix. When normalization is requested, then these are (negatively log-scaled) class posteror
 probabilities, also called the responsibility matrix in the context of mixture models.

Usage:
  classify-likelihood  (--help | --version)
  classify-likelihood  (--seqlen <file>) (--model <file>) [--coverage <file>] [--composition <file>] [--labels <file>] [--logfile <file>] [--normalize]

  -h, --help                        Show this screen
  -v, --version                     Show version
  -n, --normalize                   Output class posterior instead of the raw likelihood
  -m <file>, --model <file>         Pre-calculated classificaton model file
  -s <file>, --seqlen <file>        Sequence lengths file
  -d <file>, --coverage <file>      Differential mean coverage data file for Binomial Model
  -c <file>, --composition <file>   Compositional data (numeric) file for Naive Bayes Model
  -t <file>, --labels <file>        Label-type data file (e.g. a taxonomic path) for Hierarchical Naive Bayes Model
  -l <file>, --logfile <file>       File for logging
"""

# TODO: support multiple arguments of the same kind, like multiple label input data

__author__ = "johannes.droege@uni-duesseldorf.de"
__version__ = "bla"

import common
import composition
import binomial
import labeldist
import numpy as np
import sys

if __name__ == "__main__":
    from docopt import docopt
    argument = docopt(__doc__, version=__version__)
    common.handle_broken_pipe()

    seqlen = common.load_seqlens_file(argument["--seqlen"])
    model = common.load_model_file(argument["--model"])
    data = common.UniversalData()

    for arg, submodule, data_opts in (
                ("--coverage", binomial, {}),
                ("--composition", composition, {}),
                ("--labels", labeldist, {})):

        filename = argument[arg]

        if filename:
            model_obj = model[len(data)]
            # print(model_obj.context, file=sys.stderr)
            # print(model_obj.labels, file=sys.stderr)
            data_obj = submodule.load_data_file(filename, context=model_obj.context, **data_opts)
            # print(model_obj.context, file=sys.stderr)
            # print(model_obj.labels, file=sys.stderr)
            model_obj.update_context()
            data.append(data_obj)
            # print(data_obj.context, file=sys.stderr)

    mat = model.log_likelihood(data)

    if argument["--normalize"]:
        mat = common.exp_normalize(mat)
        common.write_probmatrix(np.log(mat, dtype=common.logprob_type), file=sys.stdout)
    else:
        common.write_probmatrix(mat, file=sys.stdout)
